### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jessrussell** [openai/universe-windows-envs#2]
There's no license mentioned, and a lot of code is marked NVIDIA proprietary. Is this project open source?

**Comment by jamesdenney** [comment]
I removed all the NVIDIA licensing agreement stuff.  Sorry that shouldn't have been in there.  Let me know if I missed any.

**Comment by jessrussell** [comment]
In order for anyone to use or redistribute this code a license needs to be included. Can you clarify what license this code is released under?

**Comment by crizCraig** [comment]
Thanks @jamesdenney, @jessrussell - Added MIT license.
