### ISSUE TITLE
XboxOne Wireless Controller

### ISSUE THREAD

**Issue by monajalal** [openai/universe-windows-envs#4]
What should I do if I have XboxOne Wireless Controller instead of Xbox360 controller for setup? Can you please add a note in the instruction of **`Xbox360ce setup`**?

**Comment by crizCraig** [comment]
hi @monajalal, so you actually don't need a physical xbox 360 controller. Xbox360ce just allows us to control the joystick via Vjoy, a programmatic joystick.
