### ISSUE TITLE
C:\Workspace\universe

### ISSUE THREAD

**Issue by monajalal** [openai/universe-windows-envs#7]
In the following command:
`setx PYTHONPATH "C:\tools\python2;C:\tools\python2\Lib;C:\tools\python2\DLLs;C:\tools\python2\Lib\lib-tk;C:\Workspace\universe" -m`
 
Which I had to use:
`setx PYTHONPATH "C:\Python27;C:\Python27\Lib;C:\Python27\DLLs;C:\Python2\Lib\lib-tk;C:\Workspace\universe" -m `
`SUCCESS: Specified value was saved.
`instead, where does `C:\Workspace\universe` come from? Is there another page of setup before this guide?
https://github.com/openai/universe-windows-envs/blob/master/vnc-windows/INSTALL.md

Thank you,
Mona

**Comment by SoonminHwang** [comment]
You can download ```universe``` [here](https://www.dropbox.com/s/ljx7uiodptxr0f3/universe-windows-envs.zip?dl=1).

> Restart PowerShell
>
> ``` mkdir /Workspace ```
>
> Download the binaries (about 2GB) you'll need to control the game (including the source) _**from here**_ and extract the folder inside, universe-windows-env, to C:\Workspace that you just created.

And if you use another language pack for window (Not english), you may modify few lines of code in ```universe```.

``` 
In universe/vnc-gtav/run_vnc_env.py, Line 64: p.['Image Name'] -> p.values()[0]
In universe/vnc-gtav/enforce_version.py, Line 56: p.['Image Name'] -> p.values()[0] 
```

**Comment by monajalal** [comment]
I just realized that in what follows in the tutorial it is mentioned to download Universe. I think I got confused due to order of tutorial. Thanks!
